-- MySQL Script generated by MySQL Workbench
-- 06/24/16 15:02:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema transporte
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `transporte` ;

-- -----------------------------------------------------
-- Schema transporte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transporte` DEFAULT CHARACTER SET latin1 ;
USE `transporte` ;

-- -----------------------------------------------------
-- Table `transporte`.`lic_dare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`lic_dare` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `data_pagamento` DATE NULL DEFAULT NULL,
  `numero` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_pagamento` VARCHAR(255) NULL DEFAULT NULL,
  `valor` DECIMAL(19,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crv_municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crv_municipio` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cod_ibge` VARCHAR(40) NOT NULL,
  `nome` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 246
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crc_empresa_transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crc_empresa_transporte` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `checklist` BIT(1) NULL DEFAULT NULL,
  `cnpj` VARCHAR(255) NOT NULL,
  `data_alteracao` DATETIME NOT NULL,
  `data_inclusao` DATETIME NOT NULL,
  `email_principal` VARCHAR(255) NOT NULL,
  `endereco_principal` VARCHAR(255) NOT NULL,
  `inscricao_estadual` VARCHAR(20) NOT NULL,
  `isencao_imposto` BIT(1) NOT NULL,
  `nomeFantasia` VARCHAR(255) NULL DEFAULT NULL,
  `obs` TEXT NULL DEFAULT NULL,
  `razaoSocial` VARCHAR(255) NOT NULL,
  `registro_agr` BIGINT(20) NOT NULL,
  `registro_embratur` VARCHAR(255) NULL DEFAULT NULL,
  `telefone_principal` VARCHAR(255) NOT NULL,
  `crc_municipio_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_qat4x95foo0aa647rmop3ovic` (`cnpj` ASC),
  UNIQUE INDEX `UK_bre9bohnxmb3jt4wwd2o7rul2` (`registro_agr` ASC),
  INDEX `FK_gnce9tn6jhrt7m7nhia2jchfv` (`crc_municipio_id` ASC),
  CONSTRAINT `FK_gnce9tn6jhrt7m7nhia2jchfv`
    FOREIGN KEY (`crc_municipio_id`)
    REFERENCES `transporte`.`crv_municipio` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crc_vistoriadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crc_vistoriadora` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `checklist` BIT(1) NULL DEFAULT NULL,
  `cnpj` VARCHAR(255) NOT NULL,
  `email_principal` VARCHAR(255) NOT NULL,
  `endereco_principal` VARCHAR(255) NOT NULL,
  `nome_fantasia` VARCHAR(255) NOT NULL,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  `razao_social` VARCHAR(255) NOT NULL,
  `registro_agr` BIGINT(20) NOT NULL,
  `registro_inmetro` VARCHAR(255) NOT NULL,
  `status_vistoriadora` BIT(1) NOT NULL,
  `telefone_principal` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_bsi8joj9ygi9f7u5cqgn0j35q` (`cnpj` ASC),
  UNIQUE INDEX `UK_bmjiew3pcvxfrsvggjpuqwgxj` (`registro_agr` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crc_crc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crc_crc` (
  `numero` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `codigoVerificacao` VARCHAR(255) NULL DEFAULT NULL,
  `data_inativacao` DATE NULL DEFAULT NULL,
  `data_inclusao` DATE NULL DEFAULT NULL,
  `data_validade` DATE NULL DEFAULT NULL,
  `inclusaoModalidade` BIT(1) NULL DEFAULT NULL,
  `numero_processo` VARCHAR(255) NOT NULL,
  `obs` TEXT NULL DEFAULT NULL,
  `resolucao` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL,
  `validador` VARCHAR(255) NULL DEFAULT NULL,
  `lic_dare_id` BIGINT(20) NULL DEFAULT NULL,
  `empresa_transporte_id` BIGINT(20) NULL DEFAULT NULL,
  `vistoriadora_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`numero`),
  INDEX `FK_644kpjixi2texg6drae6vo28j` (`lic_dare_id` ASC),
  INDEX `FK_bci4q4494lyjrimr7bp8kt0g7` (`empresa_transporte_id` ASC),
  INDEX `FK_c9hjihnxc4k3qyjms9irdw8rx` (`vistoriadora_id` ASC),
  CONSTRAINT `FK_644kpjixi2texg6drae6vo28j`
    FOREIGN KEY (`lic_dare_id`)
    REFERENCES `transporte`.`lic_dare` (`id`),
  CONSTRAINT `FK_bci4q4494lyjrimr7bp8kt0g7`
    FOREIGN KEY (`empresa_transporte_id`)
    REFERENCES `transporte`.`crc_empresa_transporte` (`id`),
  CONSTRAINT `FK_c9hjihnxc4k3qyjms9irdw8rx`
    FOREIGN KEY (`vistoriadora_id`)
    REFERENCES `transporte`.`crc_vistoriadora` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crc_atividades_crc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crc_atividades_crc` (
  `crc_crc_id` BIGINT(20) NOT NULL,
  `atividade_crc` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FK_8k4iu1tv0djey89611c6t818p` (`crc_crc_id` ASC),
  CONSTRAINT `FK_8k4iu1tv0djey89611c6t818p`
    FOREIGN KEY (`crc_crc_id`)
    REFERENCES `transporte`.`crc_crc` (`numero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crc_cnpj_registroagr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crc_cnpj_registroagr` (
  `reg_agr` VARCHAR(255) NULL DEFAULT NULL,
  `cnpj` VARCHAR(255) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `transporte`.`crc_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crc_documento` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crv_marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crv_marca` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_cq7ra8w5ypx33ry62k6n8kun1` (`descricao` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crv_modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crv_modelo` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(60) NOT NULL,
  `marca_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_6naecw69pxvl6s0vhalqq1mxo` (`descricao` ASC),
  INDEX `FK_hq8vbigokuyk8e54l7yjin784` (`marca_id` ASC),
  CONSTRAINT `FK_hq8vbigokuyk8e54l7yjin784`
    FOREIGN KEY (`marca_id`)
    REFERENCES `transporte`.`crv_marca` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crv_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crv_veiculo` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ano_modelo` VARCHAR(10) NOT NULL,
  `cap_passageiros` INT(11) NOT NULL,
  `chassi` VARCHAR(45) NOT NULL,
  `data_inclusao` DATETIME NOT NULL,
  `data_alteracao` DATETIME NULL DEFAULT NULL,
  `escolar` BIT(1) NULL DEFAULT NULL,
  `numero_crlv` VARCHAR(45) NOT NULL,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  `placa` VARCHAR(8) NOT NULL,
  `proprietario` VARCHAR(255) NOT NULL,
  `renavam` VARCHAR(20) NOT NULL,
  `restricao` VARCHAR(255) NULL DEFAULT NULL,
  `socio_razao_social` BIT(1) NOT NULL,
  `status` VARCHAR(40) NOT NULL,
  `tipo_veiculo` VARCHAR(255) NOT NULL,
  `veiculo_validado` BIT(1) NOT NULL,
  `crc_empresa_transporte_id` BIGINT(20) NULL DEFAULT NULL,
  `crv_marca_carroceria_id` BIGINT(20) NULL DEFAULT NULL,
  `crv_modelo_id` BIGINT(20) NULL DEFAULT NULL,
  `crv_municipio_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_6omnt6dbl6gnqhqo6tmdrwsod` (`crc_empresa_transporte_id` ASC),
  INDEX `FK_608rbwbuqd9epu7je6530u5i` (`crv_marca_carroceria_id` ASC),
  INDEX `FK_od28ij11jdbdl38bkb13lty5c` (`crv_modelo_id` ASC),
  INDEX `FK_1w9hllfknumxegance08hpr0w` (`crv_municipio_id` ASC),
  CONSTRAINT `FK_1w9hllfknumxegance08hpr0w`
    FOREIGN KEY (`crv_municipio_id`)
    REFERENCES `transporte`.`crv_municipio` (`id`),
  CONSTRAINT `FK_608rbwbuqd9epu7je6530u5i`
    FOREIGN KEY (`crv_marca_carroceria_id`)
    REFERENCES `transporte`.`crv_marca` (`id`),
  CONSTRAINT `FK_6omnt6dbl6gnqhqo6tmdrwsod`
    FOREIGN KEY (`crc_empresa_transporte_id`)
    REFERENCES `transporte`.`crc_empresa_transporte` (`id`),
  CONSTRAINT `FK_od28ij11jdbdl38bkb13lty5c`
    FOREIGN KEY (`crv_modelo_id`)
    REFERENCES `transporte`.`crv_modelo` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crv_vistoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crv_vistoria` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `data_laudo` DATETIME NULL DEFAULT NULL,
  `data_solicitacao` DATETIME NOT NULL,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL,
  `data_validade` DATETIME NULL DEFAULT NULL,
  `veiculoZero` BIT(1) NULL DEFAULT NULL,
  `vistoriadora_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_l2h5ap9rb98j0n214s7vilgkp` (`vistoriadora_id` ASC),
  CONSTRAINT `FK_l2h5ap9rb98j0n214s7vilgkp`
    FOREIGN KEY (`vistoriadora_id`)
    REFERENCES `transporte`.`crc_vistoriadora` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crv_crv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crv_crv` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `codigo_verificacao` VARCHAR(255) NULL DEFAULT NULL,
  `data_inativacao` DATETIME NULL DEFAULT NULL,
  `data_inclusao` DATETIME NULL DEFAULT NULL,
  `data_vencimento` DATETIME NULL DEFAULT NULL,
  `numero_processo` VARCHAR(255) NULL DEFAULT NULL,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL,
  `tipo_cadastro` VARCHAR(45) NULL DEFAULT NULL,
  `validador` VARCHAR(255) NULL DEFAULT NULL,
  `lic_dare_id` BIGINT(20) NULL DEFAULT NULL,
  `crv_empresa_transporte_id` BIGINT(20) NULL DEFAULT NULL,
  `crv_veiculo_id` BIGINT(20) NULL DEFAULT NULL,
  `crv_vistoria_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_gnjlvp3d50olhf38l8b8iweyf` (`lic_dare_id` ASC),
  INDEX `FK_i0np44ah8s1d1h2cvhpmy1ssx` (`crv_empresa_transporte_id` ASC),
  INDEX `FK_kt2s9hkjji1q4n514f48lfnk7` (`crv_veiculo_id` ASC),
  INDEX `FK_y01dlo637jtrxi7qjwaa5x0x` (`crv_vistoria_id` ASC),
  CONSTRAINT `FK_gnjlvp3d50olhf38l8b8iweyf`
    FOREIGN KEY (`lic_dare_id`)
    REFERENCES `transporte`.`lic_dare` (`id`),
  CONSTRAINT `FK_i0np44ah8s1d1h2cvhpmy1ssx`
    FOREIGN KEY (`crv_empresa_transporte_id`)
    REFERENCES `transporte`.`crc_empresa_transporte` (`id`),
  CONSTRAINT `FK_kt2s9hkjji1q4n514f48lfnk7`
    FOREIGN KEY (`crv_veiculo_id`)
    REFERENCES `transporte`.`crv_veiculo` (`id`),
  CONSTRAINT `FK_y01dlo637jtrxi7qjwaa5x0x`
    FOREIGN KEY (`crv_vistoria_id`)
    REFERENCES `transporte`.`crv_vistoria` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crv_atividades_crv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crv_atividades_crv` (
  `crv_crv_id` BIGINT(20) NOT NULL,
  `atividade_crv` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FK_8kjm3a98qbhi7673r7s246k65` (`crv_crv_id` ASC),
  CONSTRAINT `FK_8kjm3a98qbhi7673r7s246k65`
    FOREIGN KEY (`crv_crv_id`)
    REFERENCES `transporte`.`crv_crv` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crv_atividades_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crv_atividades_veiculo` (
  `crv_veiculo_id` BIGINT(20) NOT NULL,
  `atividade_veiculo` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FK_ihesyq6xqv9jvhub67pgfhruw` (`crv_veiculo_id` ASC),
  CONSTRAINT `FK_ihesyq6xqv9jvhub67pgfhruw`
    FOREIGN KEY (`crv_veiculo_id`)
    REFERENCES `transporte`.`crv_veiculo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crv_registro_baixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crv_registro_baixa` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `data_baixa` DATETIME NOT NULL,
  `data_inclusao` DATETIME NULL DEFAULT NULL,
  `data_inclusao_nova_empresa` DATETIME NULL DEFAULT NULL,
  `nomeUsuarioAutor` VARCHAR(255) NULL DEFAULT NULL,
  `crc_empresa_transporte_id` BIGINT(20) NULL DEFAULT NULL,
  `crv_veiculo_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_mvrv890xgyxyy0iykay5ryyds` (`crc_empresa_transporte_id` ASC),
  INDEX `FK_5kaxpjs7hdwdqf8t24qnd7ssj` (`crv_veiculo_id` ASC),
  CONSTRAINT `FK_5kaxpjs7hdwdqf8t24qnd7ssj`
    FOREIGN KEY (`crv_veiculo_id`)
    REFERENCES `transporte`.`crv_veiculo` (`id`),
  CONSTRAINT `FK_mvrv890xgyxyy0iykay5ryyds`
    FOREIGN KEY (`crc_empresa_transporte_id`)
    REFERENCES `transporte`.`crc_empresa_transporte` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crv_seguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crv_seguradora` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `situacao` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_oduphtaj1lo9eklq030d815rw` (`nome` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`crv_seguro_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`crv_seguro_veiculo` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(18) NOT NULL,
  `numero` VARCHAR(30) NOT NULL,
  `situacao` VARCHAR(7) NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `vigencia` DATE NOT NULL,
  `seguradora_id` BIGINT(20) NULL DEFAULT NULL,
  `veiculo_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_jbq7g8jucn569acoxjv18cl3g` (`seguradora_id` ASC),
  INDEX `FK_9udb4gqjkts6xccvth4x2lwdq` (`veiculo_id` ASC),
  CONSTRAINT `FK_9udb4gqjkts6xccvth4x2lwdq`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `transporte`.`crv_veiculo` (`id`),
  CONSTRAINT `FK_jbq7g8jucn569acoxjv18cl3g`
    FOREIGN KEY (`seguradora_id`)
    REFERENCES `transporte`.`crv_seguradora` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`lic_itinerario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`lic_itinerario` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `extensao_total` DECIMAL(19,2) NULL DEFAULT NULL,
  `horario_partida` TIME NULL DEFAULT NULL,
  `horario_retorno` TIME NULL DEFAULT NULL,
  `tipo_viagem` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`lic_nota_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`lic_nota_fiscal` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `data_emissao` DATETIME NULL DEFAULT NULL,
  `numero` VARCHAR(255) NULL DEFAULT NULL,
  `serie` VARCHAR(255) NULL DEFAULT NULL,
  `valor` DECIMAL(19,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`lic_viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`lic_viagem` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `dados_passageiros` TEXT NULL DEFAULT NULL,
  `dataPrimeiraViagem` DATETIME NULL DEFAULT NULL,
  `dias_mes` TEXT NULL DEFAULT NULL,
  `identificacao_contratante` VARCHAR(255) NULL DEFAULT NULL,
  `lotacao` INT(11) NULL DEFAULT NULL,
  `nome_contratante` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_passageiro` VARCHAR(255) NULL DEFAULT NULL,
  `lic_itinerario_id` BIGINT(20) NULL DEFAULT NULL,
  `lic_nota_fiscal_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_8b4j9l74snnfqlyu12dt0ybow` (`lic_itinerario_id` ASC),
  INDEX `FK_kckw5x11tcumaxvrv0g317ehd` (`lic_nota_fiscal_id` ASC),
  CONSTRAINT `FK_8b4j9l74snnfqlyu12dt0ybow`
    FOREIGN KEY (`lic_itinerario_id`)
    REFERENCES `transporte`.`lic_itinerario` (`id`),
  CONSTRAINT `FK_kckw5x11tcumaxvrv0g317ehd`
    FOREIGN KEY (`lic_nota_fiscal_id`)
    REFERENCES `transporte`.`lic_nota_fiscal` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`lic_licenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`lic_licenca` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `codigo_verificacao` VARCHAR(255) NULL DEFAULT NULL,
  `data_emissao` DATETIME NULL DEFAULT NULL,
  `data_inativacao` DATETIME NULL DEFAULT NULL,
  `data_solicitacao` DATETIME NULL DEFAULT NULL,
  `data_validade` DATETIME NULL DEFAULT NULL,
  `licenca_especial` BIT(1) NULL DEFAULT NULL,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  `situacao_licenca` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_atividade` VARCHAR(255) NULL DEFAULT NULL,
  `usuario_emissor` VARCHAR(255) NULL DEFAULT NULL,
  `validador` VARCHAR(255) NULL DEFAULT NULL,
  `valor` DECIMAL(19,2) NULL DEFAULT NULL,
  `lic_dare_id` BIGINT(20) NULL DEFAULT NULL,
  `crv_veiculo_id` BIGINT(20) NULL DEFAULT NULL,
  `lic_viagem_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_hbf7yhgg95yvmk88yec6mkrj2` (`lic_dare_id` ASC),
  INDEX `FK_6n27q3muvdpknb444qarwx1pn` (`crv_veiculo_id` ASC),
  INDEX `FK_a343kplqynuh6q6o20fkb8dfe` (`lic_viagem_id` ASC),
  CONSTRAINT `FK_6n27q3muvdpknb444qarwx1pn`
    FOREIGN KEY (`crv_veiculo_id`)
    REFERENCES `transporte`.`crv_veiculo` (`id`),
  CONSTRAINT `FK_a343kplqynuh6q6o20fkb8dfe`
    FOREIGN KEY (`lic_viagem_id`)
    REFERENCES `transporte`.`lic_viagem` (`id`),
  CONSTRAINT `FK_hbf7yhgg95yvmk88yec6mkrj2`
    FOREIGN KEY (`lic_dare_id`)
    REFERENCES `transporte`.`lic_dare` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`lic_anexos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`lic_anexos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `caminho` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `lic_licenca_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_oqg1q4877xroolnugmnd9q8f8` (`lic_licenca_id` ASC),
  CONSTRAINT `FK_oqg1q4877xroolnugmnd9q8f8`
    FOREIGN KEY (`lic_licenca_id`)
    REFERENCES `transporte`.`lic_licenca` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`lic_trecho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`lic_trecho` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `destino` VARCHAR(255) NULL DEFAULT NULL,
  `distancia_rodoviaria` DECIMAL(19,2) NULL DEFAULT NULL,
  `distancia_trevo` DECIMAL(19,2) NULL DEFAULT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  `origem` VARCHAR(255) NULL DEFAULT NULL,
  `situacao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5185
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`lic_itinerario_trecho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`lic_itinerario_trecho` (
  `itinerario_id` BIGINT(20) NOT NULL,
  `trecho_id` BIGINT(20) NOT NULL,
  INDEX `FK_kmf9r55xva9ddgvq3whj48g3g` (`trecho_id` ASC),
  INDEX `FK_1td9yit70d386141vni74br8q` (`itinerario_id` ASC),
  CONSTRAINT `FK_1td9yit70d386141vni74br8q`
    FOREIGN KEY (`itinerario_id`)
    REFERENCES `transporte`.`lic_itinerario` (`id`),
  CONSTRAINT `FK_kmf9r55xva9ddgvq3whj48g3g`
    FOREIGN KEY (`trecho_id`)
    REFERENCES `transporte`.`lic_trecho` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`lic_motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`lic_motorista` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `motorista` VARCHAR(255) NOT NULL,
  `numero_cnh` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`lic_tarifa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`lic_tarifa` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `aliquota` DECIMAL(19,2) NULL DEFAULT NULL,
  `preco_quilometro` DECIMAL(19,2) NULL DEFAULT NULL,
  `tipo_atividade` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_veiculo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transporte`.`lic_viagem_lic_motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`lic_viagem_lic_motorista` (
  `lic_viagem_id` BIGINT(20) NOT NULL,
  `lic_motorista_id` BIGINT(20) NOT NULL,
  INDEX `FK_p2kpvsflosv3vidh3um2mmrk6` (`lic_motorista_id` ASC),
  INDEX `FK_neh8ofex0l1ainopxfbim7g0s` (`lic_viagem_id` ASC),
  CONSTRAINT `FK_neh8ofex0l1ainopxfbim7g0s`
    FOREIGN KEY (`lic_viagem_id`)
    REFERENCES `transporte`.`lic_viagem` (`id`),
  CONSTRAINT `FK_p2kpvsflosv3vidh3um2mmrk6`
    FOREIGN KEY (`lic_motorista_id`)
    REFERENCES `transporte`.`lic_motorista` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `transporte` ;

-- -----------------------------------------------------
-- procedure atualiza_certificados
-- -----------------------------------------------------

DELIMITER $$
USE `transporte`$$
CREATE DEFINER=`root`@`%` PROCEDURE `atualiza_certificados`()
BEGIN

	DECLARE data_corrente TIMESTAMP DEFAULT current_timestamp;
    
    /*CERTIFICADO DE REGISTRO CADASTRAL */
    update crc_crc set status = 'Vencido' where data_validade < data_corrente and status = 'Ativo';
    
    /*CERTIFICADO DE REGISTRO DO VEÍCULO*/
	update crv_crv set status = 'Vencido' where data_vencimento < data_corrente and status = 'Ativo';
    
    /*VISTORIA*/
    update crv_vistoria set status = 'Inativa' where data_validade < data_corrente and status = 'Ativa';
    
    /*LICENÇA*/
    update lic_licenca set situacao_licenca = 'Vencido' WHERE data_validade < data_corrente and situacao_licenca = 'Ativo';


END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
