-- MySQL Script generated by MySQL Workbench
-- 06/27/16 07:38:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cadastrounico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cadastrounico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadastrounico` DEFAULT CHARACTER SET latin1 ;
USE `cadastrounico` ;

-- -----------------------------------------------------
-- Table `cadastrounico`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`perfil` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ativo` BIT(1) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`usuario` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ativo` BIT(1) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `senhaTemporaria` BIT(1) NULL DEFAULT NULL,
  `usuarioInterno` BIT(1) NULL DEFAULT NULL,
  `perfil_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_5171l57faosmj8myawaucatdw` (`email` ASC),
  UNIQUE INDEX `UK_pm3f4m4fqv89oeeeac4tbe2f4` (`login` ASC),
  INDEX `FK_3gsqha3puu1ccw81jefi4j71t` (`perfil_id` ASC),
  CONSTRAINT `FK_3gsqha3puu1ccw81jefi4j71t`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `cadastrounico`.`perfil` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`auditoria` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descricao` LONGTEXT NULL DEFAULT NULL,
  `entidade` VARCHAR(100) NULL DEFAULT NULL,
  `hora` DATETIME NULL DEFAULT NULL,
  `autor_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_tdbpdcfqv2ctmmlranguqtdja` (`autor_id` ASC),
  CONSTRAINT `FK_tdbpdcfqv2ctmmlranguqtdja`
    FOREIGN KEY (`autor_id`)
    REFERENCES `cadastrounico`.`usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`pessoa` (
  `tipo_pessoa` VARCHAR(31) NOT NULL,
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`email` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  `pessoa_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_d743227nc3exlnup44od6a1cq` (`pessoa_id` ASC),
  CONSTRAINT `FK_d743227nc3exlnup44od6a1cq`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `cadastrounico`.`pessoa` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`endereco` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  `uf` VARCHAR(3) NOT NULL,
  `pessoa_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_n9k2xt758al88wmlnwemyfndq` (`pessoa_id` ASC),
  CONSTRAINT `FK_n9k2xt758al88wmlnwemyfndq`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `cadastrounico`.`pessoa` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`permissao` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ativo` BIT(1) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`perfis_permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`perfis_permissoes` (
  `perfil_id` BIGINT(20) NOT NULL,
  `permissao_id` BIGINT(20) NOT NULL,
  INDEX `FK_1dbwb4a3ydfwc9x8e5qvj2c9v` (`permissao_id` ASC),
  INDEX `FK_iy2hbo13sgaeec20a4o1rriun` (`perfil_id` ASC),
  CONSTRAINT `FK_1dbwb4a3ydfwc9x8e5qvj2c9v`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `cadastrounico`.`permissao` (`id`),
  CONSTRAINT `FK_iy2hbo13sgaeec20a4o1rriun`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `cadastrounico`.`perfil` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`pessoa_fisica` (
  `cpf` VARCHAR(20) NOT NULL,
  `nacionalidade` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_1xbamx9axtft6c9hfxmaumr0k`
    FOREIGN KEY (`id`)
    REFERENCES `cadastrounico`.`pessoa` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`pessoa_juridica` (
  `cnpj` VARCHAR(20) NOT NULL,
  `data_inclusao` DATETIME NULL DEFAULT NULL,
  `data_alteracao` DATETIME NULL DEFAULT NULL,
  `inscricao_estadual` VARCHAR(20) NOT NULL,
  `nome_fantasia` VARCHAR(255) NOT NULL,
  `razao_social` VARCHAR(255) NOT NULL,
  `situacao_cadastro` VARCHAR(50) NULL DEFAULT NULL,
  `id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_5g7aqbsr2okfs904x38li5px4`
    FOREIGN KEY (`id`)
    REFERENCES `cadastrounico`.`pessoa` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`tipo_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`tipo_servico` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ativo` BIT(1) NULL DEFAULT NULL,
  `descricao_servico` VARCHAR(255) NOT NULL,
  `servico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`tipo_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`tipo_atividade` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `atividade` VARCHAR(100) NOT NULL,
  `ativo` BIT(1) NULL DEFAULT NULL,
  `descricao_atividade` VARCHAR(255) NOT NULL,
  `servico_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_kchy4hpwy1r2sidb7eicva63d` (`servico_id` ASC),
  CONSTRAINT `FK_kchy4hpwy1r2sidb7eicva63d`
    FOREIGN KEY (`servico_id`)
    REFERENCES `cadastrounico`.`tipo_servico` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`pessoa_juridica_atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`pessoa_juridica_atividades` (
  `pessoa_juridica_id` BIGINT(20) NOT NULL,
  `atividade_id` BIGINT(20) NOT NULL,
  INDEX `FK_e1qh3wnygdy79ytuqx7jiabg9` (`atividade_id` ASC),
  INDEX `FK_lgh8jlbb822n66wdf46b802e` (`pessoa_juridica_id` ASC),
  CONSTRAINT `FK_e1qh3wnygdy79ytuqx7jiabg9`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `cadastrounico`.`tipo_atividade` (`id`),
  CONSTRAINT `FK_lgh8jlbb822n66wdf46b802e`
    FOREIGN KEY (`pessoa_juridica_id`)
    REFERENCES `cadastrounico`.`pessoa_juridica` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`resolucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`resolucao` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `numero_resolucao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`pessoa_juridica_resolucoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`pessoa_juridica_resolucoes` (
  `pessoa_juridica_id` BIGINT(20) NOT NULL,
  `resolucao_id` BIGINT(20) NOT NULL,
  INDEX `FK_aw1emjbi50apgciyb3kewgf7c` (`resolucao_id` ASC),
  INDEX `FK_t0igj5a8v83ylryppph4rnv38` (`pessoa_juridica_id` ASC),
  CONSTRAINT `FK_aw1emjbi50apgciyb3kewgf7c`
    FOREIGN KEY (`resolucao_id`)
    REFERENCES `cadastrounico`.`resolucao` (`id`),
  CONSTRAINT `FK_t0igj5a8v83ylryppph4rnv38`
    FOREIGN KEY (`pessoa_juridica_id`)
    REFERENCES `cadastrounico`.`pessoa_juridica` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`pessoa_juridica_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`pessoa_juridica_servicos` (
  `pessoa_juridica_id` BIGINT(20) NOT NULL,
  `servico_id` BIGINT(20) NOT NULL,
  INDEX `FK_ddgyucybik3pmk6ix3p3epmgy` (`servico_id` ASC),
  INDEX `FK_oei4v4a3y6efnnuohafvfgx7m` (`pessoa_juridica_id` ASC),
  CONSTRAINT `FK_ddgyucybik3pmk6ix3p3epmgy`
    FOREIGN KEY (`servico_id`)
    REFERENCES `cadastrounico`.`tipo_servico` (`id`),
  CONSTRAINT `FK_oei4v4a3y6efnnuohafvfgx7m`
    FOREIGN KEY (`pessoa_juridica_id`)
    REFERENCES `cadastrounico`.`pessoa_juridica` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`socio` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `data_entrada` DATE NOT NULL,
  `participacao` DECIMAL(19,2) NOT NULL,
  `tipoRepresentante` VARCHAR(255) NOT NULL,
  `pessoa_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_21bofvv9i4csx2pyt7hl5teul` (`pessoa_id` ASC),
  CONSTRAINT `FK_21bofvv9i4csx2pyt7hl5teul`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `cadastrounico`.`pessoa` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`pessoa_juridica_socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`pessoa_juridica_socio` (
  `pessoa_juridica_id` BIGINT(20) NOT NULL,
  `socio_id` BIGINT(20) NOT NULL,
  INDEX `FK_72lglmy9mhxcjke20bkd1ogk3` (`socio_id` ASC),
  INDEX `FK_1gc5vo8aiegtmxpq2w648ec93` (`pessoa_juridica_id` ASC),
  CONSTRAINT `FK_1gc5vo8aiegtmxpq2w648ec93`
    FOREIGN KEY (`pessoa_juridica_id`)
    REFERENCES `cadastrounico`.`pessoa_juridica` (`id`),
  CONSTRAINT `FK_72lglmy9mhxcjke20bkd1ogk3`
    FOREIGN KEY (`socio_id`)
    REFERENCES `cadastrounico`.`socio` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadastrounico`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastrounico`.`telefone` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  `telefone_cel` VARCHAR(30) NULL DEFAULT NULL,
  `telefone_fixo` VARCHAR(30) NOT NULL,
  `pessoa_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_nxg78exrr1btswp13r4f3dhyt` (`pessoa_id` ASC),
  CONSTRAINT `FK_nxg78exrr1btswp13r4f3dhyt`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `cadastrounico`.`pessoa` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
